# Generated by Django 2.0.6 on 2018-07-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('carb_comp', models.DecimalField(decimal_places=3, default=0, help_text='carbs per 100g', max_digits=5)),
                ('fat_comp', models.DecimalField(decimal_places=3, default=0, help_text='fat per 100g', max_digits=5)),
                ('protein_comp', models.DecimalField(decimal_places=3, default=0, help_text='protein per 100g', max_digits=5)),
                ('water_comp', models.DecimalField(decimal_places=3, default=0, help_text='water per 100g', max_digits=5)),
                ('serving_size', models.DecimalField(decimal_places=3, default=0, help_text='recommended serving size for this food in grams', max_digits=7)),
            ],
        ),
    ]
