# Generated by Django 2.0.6 on 2018-07-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_servings', models.CharField(help_text='number of servings of each ingredient in this dish, delimited by commas', max_length=100)),
                ('carb_total', models.DecimalField(decimal_places=3, default=0, help_text='total net carbs in grams', max_digits=5)),
                ('fat_total', models.DecimalField(decimal_places=3, default=0, help_text='total fat in grams', max_digits=5)),
                ('protein_total', models.DecimalField(decimal_places=3, default=0, help_text='total protein in grams', max_digits=5)),
                ('ingredients', models.ManyToManyField(to='dish.Ingredient')),
            ],
        ),
    ]
