# Generated by Django 2.0.6 on 2018-07-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fiber_comp',
            field=models.DecimalField(decimal_places=3, default=0, help_text='grams of fiber per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar_comp',
            field=models.DecimalField(decimal_places=3, default=0, help_text='grams of sugar per 100g', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carb_comp',
            field=models.DecimalField(decimal_places=3, default=0, help_text='grams of carbs per 100g', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_comp',
            field=models.DecimalField(decimal_places=3, default=0, help_text='grams of fat per 100g', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_comp',
            field=models.DecimalField(decimal_places=3, default=0, help_text='grams of protein per 100g', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='serving_size',
            field=models.DecimalField(decimal_places=3, default=0, help_text='recommended serving size for this ingredient in grams', max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='water_comp',
            field=models.DecimalField(decimal_places=3, default=0, help_text='grams of water per 100g', max_digits=5),
        ),
    ]
