# Generated by Django 2.0.6 on 2018-07-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_auto_20180727_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
    ]
