# Generated by Django 2.0.6 on 2018-07-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180719_0207'),
        ('dish', '0004_auto_20180727_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(to='dish.Dish')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Trainee')),
            ],
        ),
    ]
