# Generated by Django 2.0.6 on 2018-07-19 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('intensity', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Trainee')),
            ],
        ),
    ]
