# Generated by Django 2.0.6 on 2018-07-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
