# Generated by Django 2.0.6 on 2018-07-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trainee_original_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='original_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
