# Generated by Django 2.0.6 on 2018-07-12 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('Awake', 'Awake'), ('NREM1', 'Light1'), ('NREM2', 'Light2'), ('NREM3', 'Deep'), ('REM', 'REM')], default='NREM1', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('quality', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Trainee')),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep.Session'),
        ),
    ]
