# Generated by Django 2.0.6 on 2018-07-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user',
            new_name='trainee',
        ),
    ]
