# Generated by Django 2.0.6 on 2018-07-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_auto_20180712_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
