# Generated by Django 2.0.6 on 2018-07-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_auto_20180719_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='quality',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
