# Generated by Django 2.0.6 on 2018-07-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0004_auto_20180727_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='quality',
            field=models.FloatField(),
        ),
    ]
