# Generated by Django 2.0.6 on 2018-07-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
